export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOGIN_INPUT_VALIDATED = 'LOGIN_INPUT_VALIDATED';
export const REGISTER_INPUT_VALIDATED = 'REGISTER_INPUT_VALIDATED';
export const LOGIN_VALIDATION_ERROR = 'LOGIN_VALIDATION_ERROR';
export const REGISTER_VALIDATION_ERROR = 'REGISTER_VALIDATION_ERROR';
export const FETCH_REPORTS_FAIL = "FETCH_REPORTS_FAIL";
export const FETCH_REPORTS_SUCCESS = "FETCH_REPORTS_SUCCESS";
export const FETCH_REPORTS_PENDING = "FETCH_REPORTS_PENDING";

